options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - '**/**/_normalize.scss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations:
    - 1
    - exclude: ['breakpoint', 'media-breakpoint-up', 'ie11']

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 1
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties:
    - 1
    -
      exclude:
        src
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-universal-selectors: 0
  no-url-domains: 1
  no-url-protocols: 1
  no-vendor-prefixes:
    - 1
    -
      excluded-identifiers:
        - ms
  no-warn: 1
  property-units: 0

  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1

  # Name Formats
  class-name-format:
    - 1
    - convention: hyphenatedbem
    - allow-leading-underscore
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format:
    - 1
    - convention: hyphenatedbem

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 1
  brace-style: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length:
    - 1
    - style: long
  hex-notation:
    - 1
    - style: lowercase
  indentation: 1
  leading-zero: 1
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth:
    - 1
    - max-depth: 4
  property-sort-order:
    - 1
    - ignore-custom-properties: false
      order:
        - display
        - position
        - grid
        - grid-template-columns
        - grid-auto-columns
        - grid-template-rows
        - grid-auto-rows
        - grid-template
        - grid-template-areas
        - grid-auto-flow
        - grid-gap
        - grid-column-gap
        - grid-row-gap
        - flex-flow
        - flex-direction
        - flex-wrap
        - justify-items
        - justify-content
        - align-items
        - align-content
        - grid-area
        - grid-column
        - grid-row
        - grid-column-start
        - grid-column-end
        - grid-row-start
        - grid-row-end
        - order
        - flex
        - flex-grow
        - flex-shrink
        - flex-basis
        - justify-self
        - align-self
        - top
        - right
        - bottom
        - left
        - float
        - clear
        - visibility
        - opacity
        - z-index
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - outline
        - border
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-width
        - border-top-width
        - border-right-width
        - border-bottom-width
        - border-left-width
        - border-style
        - border-top-style
        - border-right-style
        - border-bottom-style
        - border-left-style
        - border-color
        - border-top-color
        - border-right-color
        - border-bottom-color
        - border-left-color
        - border-radius
        - border-top-right-radius
        - border-bottom-right-radius
        - border-bottom-left-radius
        - border-top-left-radius
        - background
        - background-color
        - background-image
        - background-repeat
        - background-position
        - background-size
        - cursor
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - overflow
        - list-style
        - caption-side
        - table-layout
        - border-collapse
        - border-spacing
        - empty-cells
        - vertical-align
        - text-align
        - text-indent
        - text-transform
        - text-decoration
        - text-decoration-color
        - line-height
        - word-spacing
        - letter-spacing
        - white-space
        - color
        - font
        - font-family
        - font-size
        - font-weight
        - content
        - quotes
  pseudo-element: 1
  quotes: 1
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
